spring.application.name=entregas-domicilio
spring.datasource.url=jdbc:mysql://localhost:3306/entregas_domicilio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=TU_CONTRASENIA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
